apiVersion: v1
appVersion: "latest"
description: A PowerDNS web interface with advanced features.
name: powerdnsadmin
version: 0.1.1
sources:
  - https://github.com/ngoduykhanh/PowerDNS-Admin
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
