apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "powerdnsadmin.fullname" . }}
  labels:
{{ include "powerdnsadmin.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "powerdnsadmin.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "powerdnsadmin.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}

    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "powerdnsadmin.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ tpl .Values.image.tag . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SQLA_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdnsadmin.fullname" . }}
                  key: postgres_host
            - name: SQLA_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdnsadmin.fullname" . }}
                  key: postgres_port
            - name: SQLA_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdnsadmin.fullname" . }}
                  key: postgres_username
            - name: SQLA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdnsadmin.fullname" . }}
                  key: postgres_password
            - name: SQLA_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "powerdnsadmin.fullname" . }}
                  key: postgres_database
          ports:
            - name: http
              containerPort: 9191
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
