apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdnsadmin.fullname" . }}
  labels:
{{ include "powerdnsadmin.labels" . | indent 4 }}
type: Opaque
data:
  postgres_host: "{{ .Values.postgres.host | b64enc }}"
  postgres_port: "{{ .Values.postgres.port | toString | b64enc }}"
  postgres_username: "{{ .Values.postgres.username | b64enc }}"
  postgres_password: "{{ .Values.postgres.password | b64enc }}"
  postgres_database: "{{ .Values.postgres.database | b64enc }}"
